esphome:
  name: esp32-letto
  friendly_name: ESP32 Letto

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Y8IrfT9VeoOft4dhabpIXjdaRQHU69KzFnDGMeQ5cjs="

ota:
  - platform: esphome
    password: "f98e9f68b3f6edede06941464246c974"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Letto Fallback Hotspot"
    password: "4B8fbelMwtWF"

captive_portal:
    