esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QL1wvvWasUhNkAQ2IKseovET+MUetRoiW7nyqGxlltw="

ota:
  - platform: esphome
    password: "33b482afb6f3ba01de8b11967cf138fa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "Qd7HU4Z4AaVW"

captive_portal:

switch:
  - platform: gpio
    pin: GPIO12
    id: relay1
    name: "Luce 1"
    inverted: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO13
    id: relay2
    name: "Luce 2"
    inverted: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO14
    id: relay3
    name: "Luce 3"
    inverted: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO15
    id: relay4
    name: "Luce 4"
    inverted: false
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    pin: GPIO32
    name: "Interruttore 1"
    on_press:
      - switch.toggle: relay1

  - platform: gpio
    pin: GPIO33
    name: "Interruttore 2"
    on_press:
      - switch.toggle: relay2

  - platform: gpio
    pin: GPIO34
    name: "Interruttore 3"
    on_press:
      - switch.toggle: relay3

  - platform: gpio
    pin: GPIO35
    name: "Interruttore 4"
    on_press:
      - switch.toggle: relay4