// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Camper_Dashboard

#ifndef _CAMPER_DASHBOARD_UI_H
#define _CAMPER_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Startup
void ui_Startup_screen_init(void);
void ui_event_Startup( lv_event_t * e);
extern lv_obj_t *ui_Startup;
extern lv_obj_t *ui_LoadingLabel;
extern lv_obj_t *ui_Spinner1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_lightbulb_yellow_png);   // assets/lightbulb_yellow.png
LV_IMG_DECLARE( ui_img_lightbulb_png);   // assets/lightbulb.png

// FONTS
LV_FONT_DECLARE( ui_font_Header);
LV_FONT_DECLARE( ui_font_Label);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
